Update bdeploy-2.yml

diff --git a/.github/workflows/bdeploy-2.yml b/.github/workflows/bdeploy-2.yml
--- a/.github/workflows/bdeploy-2.yml
+++ b/.github/workflows/bdeploy-2.yml
@@ -1,8 +1,8 @@
-name: Deploy to EKS
+name: Workflow02
 on:
   repository_dispatch:
     types:
-      - deploy_to_eks  
+      - trigger-workflow02  
 
 jobs:
   deploy:
@@ -13,7 +13,7 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Configure AWS credentials
-      uses: aws-actions/configure-aws-credentials@v1
+      uses: aws-actions/configure-aws-credentials@v2  
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -25,11 +25,21 @@ jobs:
 
     - name: Fetch Image Tag from Repo A
       run: |
-        echo "Fetched Image Tag: ${{ github.event.client_payload.image_tag }}"  # This gets the image tag sent from Repo A
+        if [[ -z "${{ github.event.client_payload.image_tag }}" ]]; then
+          echo "Image tag is not provided"
+          exit 1
+        else
+          echo "Fetched Image Tag: ${{ github.event.client_payload.image_tag }}"  # Image tag is retrieved here
+        fi
 
     - name: Update Deployment File with New Image Tag
       run: |
-        sed -i 's|image: .*|image: 058264137181.dkr.ecr.eu-west-1.amazonaws.com/github-testing:${{ github.event.client_payload.image_tag }}|' deployment.yaml
+        if [[ -f deployment.yaml ]]; then
+          sed -i'' -e 's|image: .*|image: 058264137181.dkr.ecr.eu-west-1.amazonaws.com/github-testing:${{ github.event.client_payload.image_tag }}|' deployment.yaml
+        else
+          echo "deployment.yaml file not found!"
+          exit 1
+        fi
 
     - name: Deployment completed successfully
       run: |
